<?php 

// echo $this->getRequest()->getParams('id');

// // The line ` = Mage::getModel('product/product');` is creating an instance of the `product` model in the Magento framework. This model can be used to interact with product data in the database, such as loading specific products or performing CRUD operations on products.
// $productModel = Mage::getModel('catalog/product')->load(2);
// echo '<pre>';


// // print_r($productModel->load(4));// MODEL --- RESOURCE --- COLLECTION
// print_r($productModel->getId());
// echo "<br>";


// // print_r($productModel->getProductName());
// print_r($productModel->getSku());
// print_r($productModel);

echo $this->getchildHtml(''); 

?>

<h1>Content</h1> 