<!-- Footer content here -->
<footer>
    <section id="i2nx4s" class="gjs-ft-section ft-section-box'>
        <div data-droptype=" container" id="i50b7o" class="gjs-ft-wrapper gjs-ft-wrap-normal wrapper-box">
        <div class="row text-center">
            <div class="col">
                <ul class="text-center">
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#">Contact Us</a></li>
                    <li><a href="#">Terms & Conditions</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                </ul>
            </div>
        </div>
        </div>
    </section>
    <section id="i2nx4s" class="gjs-ft-section ft-section-box">
        <div data-droptype="container" id="i50b7o" class="gjs-ft-wrapper gjs-ft-wrap-normal wrapper-box">
            <h2 id="i2sm6g" class="ftsub_heading">
                Copyrights @2024 The Sanskriti | All Rights Reserved
            </h2>
        </div>
    </section>
</footer>