    <div class="header">
        <nav>
            <a href="http://localhost/internship/mvc_project/"><img src="<?php echo Mage::getBaseUrl('skin/images/icon.png') ?>" width="100" height="80" alt="" /></a>
            <ul>
                <li>
                    <a href="http://localhost/internship/mvc_project/">Home</a>
                </li>
                <li>
                    <a href="http://localhost/internship/mvc_project/admin/catalog_product/form">Form</a>
                </li>
                <li>
                    <a href="http://localhost/internship/mvc_project/admin/catalog_category/form">Category Form</a>
                </li>
                <li>
                    <a href="http://localhost/internship/mvc_project/admin/catalog_product/list">Product List</a>
                </li>
            </ul>
        </nav>
    </div>