<div class="header">
    <nav>
        <a href="http://localhost/internship/mvc_project/"><img
                src="<?php echo Mage::getBaseUrl('skin/images/icon.png') ?>" width="100" height="80" alt="" /></a>
        <ul>
            <li>
                <a href="http://localhost/internship/mvc_project/">Home</a>
            </li>
            <li>
                <a href="http://localhost/internship/mvc_project/">Link 1</a>
            </li>
            <li>
                <a href="http://localhost/internship/mvc_project/">Link 2</a>
            </li>

            <li>
                <a href="http://localhost/internship/mvc_project/customer/account/login"><button>Customer
                        Login</button></a>
            </li>
            <li>
                <a href="http://localhost/internship/mvc_project/admin/user/login"><button>Admin Login</button></a>
            </li>
        </ul>
    </nav>
</div>