<?php

$bannerCollection = Mage::getModel('banner/banner')->getCollection();

?>

<div class="table table-bordered table-hover">
    <h1 class="table-heading">Product List</h1>
    <table>
        <thead>
            <tr class="bg-success text-center">
                <th>Id</th>
                <th>Image</th>
                <th>Status</th>
                <th>Show On</th>
                <th>UPDATE</th>
                <th>DELETE</th>
            </tr>
        </thead>
        <tbody class="text-center">
            <?php foreach ($bannerCollection->getData() as $_banner): ?>
                <tr>
                    <td>
                        <?php echo $_banner->getBannerId() ?>
                    </td>
                    <td>
                        <img src="<?php echo Mage::getBannerPath('banner/') . $_banner->getBannerImage() ?>" width=" 100"
                            height="90" alt="logo" />

                    </td>

                    <td>
                        <?php echo $_banner->getStatus() ?>
                    </td>
                    <td>
                        <?php echo $_banner->getShowOn() ?>
                    </td>
                    <td>
                        <a href="<?php echo $this->getUrl('admin/banner/form?id=' . $_banner->getbanner_id()) ?>">
                            <button name="Update" class="btn btn-primary">Update</button>
                        </a>
                    </td>
                    <td> <a href="<?php echo $this->getUrl('admin/banner/delete?id=' . $_banner->getbanner_id()); ?>">
                            <button name="delete" class="btn btn-danger">Delete</button>
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>