<!-- catalog_category table -->
<div>
    <form action="<?php echo $this->getUrl('admin/catalog_category/save') ?>" method="post">
        <div class="row">
            <div class="col-3">
                <label for="category_id">Category Id</label>
                <input type="number" name="product[category_id]"><br>

                <label for="category_name">Category Name</label>
                <input type="text" name="product[category_name]"><br>
            </div>
        </div>
        <label>Status</label>
        <input type="radio" id="enable" name="product[status]" value="enable">
        <label for="enable">Enable</label>

        <input type="radio" id="disable" name="product[status]" value="disable">
        <label for="disable">Disable</label><br>
    </form>
</div>