<!-- catalog_category table -->
<div>
    <form action="<?php echo $this->getUrl('admin/catalog_category/save') ?>" method="post">

        <?php $categoryModel = $this->getCategoryForm();
        ?>

        <div class="row">
            <div class="col-4">
                <label for="category_id">Category Id</label>
                <input type="number" name="category[category_id]"><br>

                <label for="category_name">Category Name</label>
                <input type="text" name="category[category_name]"><br>
            </div>
        </div><br>
        <label>Status</label><br>
        <div class="form-check">
            <input type="radio" id="enable" name="category[status]" value="enable">
            <label for="enable">Enable</label>


            <input type="radio" id="disable" name="category[status]" value="disable">
            <label for="disable">Disable</label><br>
        </div>
        <input type="submit" name="submit" value="submit" class="btn btn-primary"></button>
    </form>
</div>