<?php $productCollection = Mage::getModel("catalog/product")->getCollection();

?>

<div class="row justify-content-center">
    <div class="col-md-10">
        <!-- display all the products -->
        <div class="row">
            <?php foreach ($productCollection->getData() as $_product): ?>
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <a
                            href="<?php echo $this->getUrl('admin/catalog_product/view/') . '?id=' . $_product->getProductId() ?>">
                            <img src="<?php echo Mage::getImagePath('product/') . $_product->getImageLink() ?>"
                                class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title">
                                    <?php echo $_product->getName() ?>
                                </h5>
                        </a>
                        <p class="card-text">
                            <?php echo $_product->getDescription() ?>
                        </p>
                        <label for="qty">Qty</label>
                        <!-- <input type="number" name="qty" id="qty" min="0" value="0"> -->
                        <form action="<?php echo $this->getUrl('sales/quote/add') ?>" method="post">
                            <input type="hidden" name="cart[product_id]" value="<?php echo $_product->getProductId() ?>">
                            <input type="number" value="1" name="cart[qty]" min="0">
                            <button type="submit" name="submit" class="btn btn-primary" value="Add To Cart">Add to
                                Cart</button>
                        </form>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>

<div class="col-md-2 bg-secondary p-0">
    <!-- display sidenav/filters -->
    <ul class="navbar-nav me-auto text-center">
        <li class="nav-item bg-dark mr-3">
            <h3 class="text-light">Filters</h3>
        </li>
    </ul>
    <ul class="navbar-nav me-auto text-center">
        <li class="nav-item bg-info mr-3">
            <a href="#" class="nav-link text-light">
                <h4>Category</h4>
            </a>
        </li>
        <?php foreach ($categoryList as $list): ?>
            <li class="nav-item">
                <a href="#" class="nav-link text-light">
                    <?php echo $list ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>

    <ul class="navbar-nav me-auto text-center mt-4">
        <li class="nav-item bg-info mr-3">
            <a href="#" class="nav-link text-light">
                <h4>Brands</h4>
            </a>
        </li>
        <?php foreach ($brandList as $list): ?>
            <li class="nav-item">
                <a href="#" class="nav-link text-light">
                    <?php echo $list ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>


</div>
</div>
</div>