<!-- catalog_category table -->


<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <form action="" method="post">
            <div class="row">
                <div class="col-3">
                <label for="category_id">Category Id</label>
                <input type="number" name="product[category_id]" class="form-control"><br>

                <label for="category_name">Category Name</label>
                <input type="text" name="product[category_name]" class="form-control"><br>
                </div>
            </div>
            <label>Status</label>
                <input type="radio" id="enable" name="product[status]" value="enable">
                <label for="enable">Enable</label>

                <input type="radio" id="disable" name="product[status]" value="disable">
                <label for="disable">Disable</label><br>
        </form>
    </div>
</body>
</html>