<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>catalog_product</title>

</head>

<body>
    <div>
        <form action="<?php echo $this->getUrl('catalog/product/save') ?>" method="post">
            <input type="hidden" name="product[product_id]" class="form-control">
            <br>
            <div>
                <label for="sku">SKU</label>
                <input type="text" name="product[sku]" class="form-control">

                <label for="name">Name</label>
                <input type="text" name="product[name]"><br>

                <label for="color">Color</label>
                <input type="text" name="product[color]"><br>

                <label for="size">Size</label>
                <input type="text" name="product[size]"><br>

                <label for="">Description</label>
                <input type="textbox" name="product[description]"><br>

                <label for="image_link">Image Link</label>
                <input type="text" name="product[image_link]"><br>

                <label for="link">Link</label>
                <input type="text" name="product[link]"><br>

                <label for="category_id">Category ID</label>
                <input type="text" name="product[category_id]"><br>

                <label for="price">Pice</label>
                <input type="text" name="product[price]"><br>

                <label for="mfr_cost">Manufactur Cost</label>
                <input type="text" name="product[mfr_cost]"><br>

                <label for="shipping_cost">Shipping Cost</label>
                <input type="text" name="product[shipping_cost]"><br>

                <label for="total_cost">Total Cost</label>
                <input type="text" name="product[total_cost]"><br>

                <label for="margin_percentage">Margin Percentage</label>
                <input type="text" name="product[margin_percentage]"><br>

                <label for="min_price">Minimum Price</label>
                <input type="text" name="product[min_price]"><br>

                <label>Status</label>
                <input type="radio" id="enable" name="product[status]" value="enable">
                <label for="enable">Enable</label>

                <input type="radio" id="disable" name="product[status]" value="disable">
                <label for="disable">Disable</label><br>
            </div>
            <input type="submit" name="submit" value="submit" class="btn btn-primary"></button>
        </form>
    </div>
</body>

</html>