<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<div class="container">
    <table class="table">
        <head>
            <tr>
                <th>Product ID</th>
                <th>Sku</th>
                <th>Name</th>
                <th>Color</th>
                <th>Size</th>
                <th>Description</th>
                <th>Image Link</th>
                <th>Link</th>
                <th>Category Id</th>
                <th>Price</th>
                <th>Mfr Cost</th>
                <th>Shipping Cost</th>
                <th>Total Cost</th>
                <th>margin_percentage</th>
                <th>Min Price</th>

                <th>Action</th>
            </tr>      
        </head>
        <tbody>
        <?php 
                //if($run_query->num_rows>0){
                    //while($row = $run_query->fetch_assoc()){
            ?>
                        <tr>
                            <td><?php echo $row['product_id']; ?></td>
                            <td><?php echo $row['sku']; ?></td>
                            <td><?php echo $row['name']; ?></td>
                            <td><?php echo $row['color']; ?></td>
                            <td><?php echo $row['size']; ?></td>
                            <th><?php echo $row['image_link']; ?></th>
                            <th><?php echo $row['link'];?></th>
                            <th><?php echo $row['category_id'];?></th>
                            <th><?php echo $row['price'];?></th>
                            <th><?php echo $row['mfr_cost'];?></th>
                            <th><?php echo $row['shipping_cost'];?></th>
                            <th><?php echo $row['total_cost'];?></th>
                            <th><?php echo $row['margin_percentage'];?></th>
                            <th><?php echo $row['min_price'];?></th>

                            <td>
                                <a class="btn btn-info" href="update.php?id=<?php echo $row['id'];?>">
                                Edit</a>
                                <a class="btn btn-danger" href="delete.php?id=<?php echo $row['id'];?>">
                                Delete</a>
                            </td>
                        </tr>
            <?php 
                
            ?>            
        </tbody>
    </table>
</body>
</html>