<?php $salesQuoteItem = $this->getItemList()->getData();
$salesQuote = $this->getGrandTotal()->getData();
?>
<title>Cart</title>
<!-- cart + summary -->
<section class="bg-light my-5">
    <div class="container">
        <div class="row">
            <!-- cart -->
            <div class="col-lg-9"> 
                <div class="card border shadow-0">
                    <div class="m-4">
                        <h4 class="card-title mb-4">Your Shopping Cart</h4>
                        <?php foreach ($salesQuoteItem as $_itemList): ?>
                            <?php foreach ($this->getProductList($_itemList->getProductId())->getData() as $_productDetails): ?>
                                <form action="<?php echo $this->getUrl('sales/quote/update') ?>" method="post">
                                <div class="row gy-3 mb-4">

                                    <div class="col-lg-5">
                                        <div class="mr-lg-5">
                                            <div class="d-flex">
                                                <img src="<?php echo Mage::getImagePath($_productDetails->getImageLink()) ?>"
                                                    class="border rounded me-3 w-25" style="width:96; height:96;">
                                                <div>
                                                    <a href="" class="nav-link">
                                                        <?php echo $_productDetails->getName() ?>
                                                    </a>
                                                    <p class="text-muted">
                                                        <!-- properties like color,sixe,type -->
                                                        <?php echo $_productDetails->getColor() ?>
                                                        <?php echo $_productDetails->getSize() ?>
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-lg-2 col-sm-6 col-6 d-flex flex-row flex-lg-column flex-xl-row text-nowrap">
                                        <div>
                                                <input class="qty" type="number" name="update_item[qty]" value="<?php echo $_itemList->getQty() ?>"
                                                    min="1">

                                        </div>
                                        <div>
                                            <text class="h6">
                                                <?php echo $_itemList->getRowTotal() ?>
                                            </text>
                                            <br>
                                            <small class="text-muted text-nowrap">
                                                <?php echo $_productDetails->getPrice() . "/per item"; ?> price
                                            </small>
                                        </div>
                                    </div>

                                    <div
                                        class="col-lg col-sm-6 d-flex justify-content-sm-center justify-content-md-start justify-content-lg-center justify-content-xl-end mb-2">
                                        <div class="flot-md-end"><a href="#"
                                                class="btn btn-light border px-2 icon-hover-primary">
                                                <i class="fas fa-heart fa-lg px-1 text-secondary"><svg
                                                        xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                        fill="currentColor" class="bi bi-bookmark" viewBox="0 0 16 16">
                                                        <path
                                                            d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1z" />
                                                    </svg></i>
                                            </a>
                                            <a href="<?php echo $this->getUrl('sales/quote/delete/') . '?quote_id=' . $_itemList->getQuoteId() . '&item_id=' . $_itemList->getItemId() ?>"
                                                class="btn btn-light border text-danger icon-hover-danger">Remove</a></br>




                                            <button class="order-place" type="submit" name="update">Update</button>
                                            <input type="hidden" name="update_item[quote_id]"
                                                value="<?php echo $_itemList->getQuoteId() ?>" min="0">
                                            <input type="hidden" name="update_item[item_id]"
                                                value="<?php echo $_itemList->getItemId() ?>" min="0">
                                            <input type="hidden" name="update_item[product_id]"
                                                value="<?php echo $_productDetails->getProductId() ?>" min="0">
                                            </form>
                                        </div>
                                    </div>
                                </div>

                            <?php endforeach ?>
                        <?php endforeach ?>
                        <div class="border-top pt-4 mx-4 mb-4">
                            <p><i class="fas fa-truck text-muted fa-lg">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                                        class="bi bi-truck" viewBox="0 0 16 16">
                                        <path
                                            d="M0 3.5A1.5 1.5 0 0 1 1.5 2h9A1.5 1.5 0 0 1 12 3.5V5h1.02a1.5 1.5 0 0 1 1.17.563l1.481 1.85a1.5 1.5 0 0 1 .329.938V10.5a1.5 1.5 0 0 1-1.5 1.5H14a2 2 0 1 1-4 0H5a2 2 0 1 1-3.998-.085A1.5 1.5 0 0 1 0 10.5zm1.294 7.456A2 2 0 0 1 4.732 11h5.536a2 2 0 0 1 .732-.732V3.5a.5.5 0 0 0-.5-.5h-9a.5.5 0 0 0-.5.5v7a.5.5 0 0 0 .294.456M12 10a2 2 0 0 1 1.732 1h.768a.5.5 0 0 0 .5-.5V8.35a.5.5 0 0 0-.11-.312l-1.48-1.85A.5.5 0 0 0 13.02 6H12zm-9 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2m9 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2" />
                                    </svg>
                                </i>
                                Free Delivery within 1 weeks
                            </p>
                            <p class="text-muted">
                                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
                                incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
                                exercitation ullamco laboris nisi ut
                                aliquip
                            </p>
                        </div>
                    </div>
                </div>
                <!-- cart -->
            </div>
            <!-- summary -->
            <div class="col-lg-3">
                <div class="card mb-3 border shadow-0">
                    <div class="card-body">
                        <form>
                            <div class="form-group">
                                <label for="" class="form-label">Have coupon?</label>
                                <div class="input-group">
                                    <input type="text" class="form-control border" placeholder="Coupon code">
                                    <button class="btn btn-light border">Apply</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="card shadow-0 border">
                    <div class="card-body">
                        <div>
                            <div class="d-flex justify-content-between">
                                <p class="mb-2">Total price:</p>
                                <p class="mb-2">

                                    <?php foreach ($salesQuote as $gt):
                                        $tax = (($gt->getTaxPercent() / 100) * $gt->getGrandTotal());
                                        echo ($gt->getGrandTotal() - $tax) ?>
                                    </p>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <p class="mb-2">Discount:</p>
                                    <p class="mb-2 text-success">₹0
                                        <?php $discount = 0; ?>
                                    </p>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <p class="mb-2">TAX</p>
                                    <p class="mb-2">₹
                                        <?php echo $tax ?>
                                    </p>
                                </div>
                                <hr>
                                <div class="d-flex justify-content-between">
                                    <p class="mb-2">Grand total:</p>
                                    <p class="mb-2">
                                        <?php echo $gt->getGrandTotal() - $discount ?>
                                    </p>
                                </div>
                            <?php endforeach; ?>
                            <hr>
                            <div class="mt-3">
                                
                                <a href="<?php echo $this->getUrl('cart/checkout/checkout') ?>"><button  class="btn btn-success w-100 shadow-0 mb-2">Proceed to Buy</button></a>

                                <a href="<?php echo $this->getUrl('catalog/category/view') ?>"
                                    class="btn btn-light w-100 border mt-2">Shop more</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- summary -->
        </div>
    </div>
</section>