<?php $salesQuoteItem = $this->getItemList()->getData();
// print_r($salesQuoteItem);    ?>
<?php //$salesQuote = $this->getQuoteList()->getData();  ?>

<section>
    <div class="container-md border">
        <div class="row border mt-5 mb-5 ml-5 vw-10 ">

            <div class="col-7 border">
                <h5>Cart Items</h5>
                <?php foreach ($salesQuoteItem as $_itemList): ?>

                    <div class="row">
                    </div>

                <?php endforeach ?>

            </div>

            <div class="col-5 border">

                <div class="row">
                    <h5>Billing Address</h5>
                    <hr>
                </div>
                <div class="row ">
                    <h5>Shipping</h5>
                    <hr>
                </div>
                <div class="row ">
                    <h5>Payment Method</h5>
                    <hr>
                </div>
            </div>

        </div>
    </div>
</section>


































<!-- address form -->
<!-- <section>
    <div class="row">
        <div class="form-container">
            <h2>Sales Order Customer Form</h2>
            <form action="process_order_customer.php" method="POST">
                <div class="form-group">

                    <input type="hidden" id="order_id" name="order_id">
                </div>
                <div class="form-group">

                    <input type="hidden" id="customer_id" name="customer_id">
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="billing_address">Billing Address:</label>
                    <input type="textarea" rows="4" cols="50" id="billing_address" name="billing_address" required>
                </div>
                <div class="form-group">
                    <label for="billing_city">Billing City:</label>
                    <input type="text" id="billing_city" name="billing_city" required>
                </div>
                <div class="form-group">
                    <label for="billing_region">Billing Region:</label>
                    <input type="text" id="billing_region" name="billing_region">
                </div>
                <div class="form-group">
                    <label for="billing_country">Billing Country:</label>
                    <input type="text" id="billing_country" name="billing_country" required>
                </div>
                <div class="form-group">
                    <label for="billing_phone">Billing Phone:</label>
                    <input type="tel" id="billing_phone" name="billing_phone" required>
                </div class="form-group">
                <div class="form-group">
                    <label for="shipping_address">Shipping Address:</label>
                    <input type="textarea" id="shipping_address" name="shipping_address" rows="6" cols="70" required>
                </div>
                <div class="form-group">
                    <label for="shipping_city">Shipping City:</label>
                    <input type="text" id="shipping_city" name="shipping_city" required>
                </div>
                <div class="form-group">
                    <label for="shipping_region">Shipping Region:</label>
                    <input type="text" id="shipping_region" name="shipping_region">
                </div>
                <div class="form-group">
                    <label for="shipping_country">Shipping Country:</label>
                    <input type="text" id="shipping_country" name="shipping_country" required>
                </div>
                <div class="form-group">
                    <label for="shipping_phone">Shipping Phone:</label>
                    <input type="tel" id="shipping_phone" name="shipping_phone" required>
                </div>
                <div class="form-group">
                    <button type="submit">Place Order</button>
                </div>
            </form>
        </div>
    </div>
</section> -->