<body>
    <div class="login-container">
        <h2>Login</h2>
        <form action="<?php echo $this->getUrl('customer/account/login/') ?>" method="post">
            <input type="email" name="login[customer_email]" placeholder="Email" required />
            <input type="password" name="login[password]" placeholder="Password" required />
            <button type="submit">Login</button>
        </form>
        <div class="login-links">
            <a href="http://localhost/internship/mvc_project/customer/account/forgotpassword">Forgot password?</a>
            <a href="http://localhost/internship/mvc_project/customer/account/register">Register</a>
        </div>
    </div>
</body>