<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MVC Project</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <?php //$this->getChild('head')->addCss('header.css')->addCss('footer.css');         ?>
    <?php echo $this->getChildHtml('head'); ?>
</head>

<body>
    <!-- The code you provided is using PHP to echo the output of the `getChildHtml` method on the `` object. -->
    <div>
        <?php echo $this->getChildHtml('header'); ?>
    </div>
    <div>
        <?php echo $this->getChildHtml('content'); ?>
    </div>
    <div>
        <?php echo $this->getChildHtml('footer'); ?>
    </div>
    <div>
        You are in 1column.phtml
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

</body>

</html>

<!-- <form>
        <h1>hello</h1>
        <?php //echo Mage::getModel('core/request')->getParams('pid'); 
        ?> 
        <input type="text" name="acb" value="">
    </form> -->