<!-- content -->
<?php
$id = $this->getRequest()->getParams('id');
$productCollection = Mage::getModel("catalog/product")->getCollection()->addFieldToFilter('product_id', $id); ?>
<section class="py-5">
    <div class="container">
        <?php foreach ($productCollection->getData() as $_product): ?>
            <div class="row gx-5">
                <aside class="col-lg-6">
                    <div class="border rounded-4 mb-3 d-flex justify-content-center">
                        <a data-fslightbox="mygalley" class="rounded-4" target="_blank" data-type="image"
                            href="https://bootstrap-ecommerce.com/bootstrap5-ecommerce/images/items/detail1/big.webp">
                            <img style="max-width: 100%; max-height: 100vh; margin: auto;" class="rounded-4 fit"
                                src="<?php echo Mage::getImagePath($_product->getImageLink()) ?>" />
                        </a>
                    </div>
                    <!-- thumbs-wrap.// -->
                    <!-- gallery-wrap .end// -->
                </aside>
                <main class="col-lg-6">
                    <div class="ps-lg-3">
                        <h4 class="title text-dark">
                            <?php echo $_product->getName() ?>
                        </h4>
                        <div class="d-flex flex-row my-3">
                            <div class="text-warning mb-1 me-2">
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                                <i class="fas fa-star-half-alt"></i>
                                <span class="ms-1">
                                    4.5
                                </span>
                            </div>
                            <span class="text-muted"><i class="fas fa-shopping-basket fa-sm mx-1"></i>154 orders</span>
                            <span class="text-success ms-2">In stock</span>
                        </div>

                        <div class="mb-3">
                            <span class="h5">
                                <?php echo $_product->getPrice() ?>
                            </span>
                            <span class="text-muted">/per box</span>
                        </div>

                        <p>
                            <?php echo $_product->getDescription() ?>
                        </p>

                        <div class="row">
                            <dt class="col-3">Type:</dt>
                            <dd class="col-9">Regular</dd>

                            <dt class="col-3">Color</dt>
                            <dd class="col-9">
                                <?php echo $_product->getColor() ?>
                            </dd>

                            <dt class="col-3">Material</dt>
                            <dd class="col-9">Cotton, Jeans</dd>

                            <dt class="col-3">Brand</dt>
                            <dd class="col-9">Reebook</dd>
                        </div>

                        <hr />

                        <div class="row mb-4">
                            <div class="col-md-4 col-6">
                                <label class="mb-2">Size</label>
                                <select class="form-select border border-secondary" style="height: 35px;">
                                    <option>Small</option>
                                    <option>Medium</option>
                                    <option>Large</option>
                                </select>
                            </div>
                            <!-- col.// -->
                            <div class="col-md-4 col-6 mb-3">
                                <label class="mb-2 d-block">Quantity</label>
                                <div class="input-group mb-3" style="width: 170px;">
                                    <button class="btn btn-white border border-secondary px-3" type="button"
                                        id="button-addon1" data-mdb-ripple-color="dark">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                    <input type="text" class="form-control text-center border border-secondary"
                                        placeholder="14" aria-label="Example text with button addon"
                                        aria-describedby="button-addon1" />
                                    <button class="btn btn-white border border-secondary px-3" type="button"
                                        id="button-addon2" data-mdb-ripple-color="dark">
                                        <i class="fas fa-plus"></i>
                                    </button>
                                </div>
                            </div>



                            <div class="row mb-4">
                                <div class="col-md-7 col-6 mb-3">
                                    <form action="<?php echo $this->getUrl('sales/quote/add') ?>" method="post">
                                        <input type="hidden" name="cart[product_id]"
                                            value="<?php echo $_product->getProductID() ?>">
                                        <input type="hidden" value="1" name="cart[qty]">
                                        <button style="width: 7vw" type="submit" name="submit" class="btn btn-primary"
                                            value="Add To Cart">Add
                                            to
                                            Cart</button>
                                    </form>
                                </div>
                                <!-- col.// -->
                                <div class="col-md-4 col-6 mb-3">

                                    <div class="input-group mb-3" style="width: 170px;">
                                        <a href="#" class="btn btn-light border border-secondary py-2 icon-hover px-3">
                                            <i class="me-1 fa fa-heart fa-lg"></i> Add to wishList </a>
                                    </div>
                                </div>

                            </div>

                        </div>
                </main>
            </div>
        <?php endforeach; ?>
    </div>