<div class="sidebar">
    <h2> Admin Panel </h2>
    <br>
    <ul>
        <li><a href="<?php echo Mage::getBaseUrl('') ?>"> HOME </a></li>
        <li><a href="<?php echo Mage::getBaseUrl('admin/catalog_product/list') ?>"> PRODUCT </a></li>
        <li><a href="<?php echo Mage::getBaseUrl('admin/catalog_category/list') ?>"> CATEGORY </a></li>
        <!-- <li><a href="<? php// echo Mage::getBaseUrl('customer/account/dashboard')  ?>"> USERS </a></li> -->
        <li><a href="<?php echo Mage::getBaseUrl('admin/banner_banner/add') ?>"> BANNER </a></li>
        <li><a href="#"><button>Log Out</button></a></li>
    </ul>
</div>