<div class="container">
    <!-- <div class="image-container"> -->
    <!-- Placeholder image -->
    <!-- <img src="" alt=""> -->
    <!-- </div> -->
    <div class="form-container">
        <h2>Admin Login</h2>
        <form action="<?php echo $this->getUrl('admin/user/login') ?>" method="POST">
            <div class="form-group">
                <input type="hidden" id="admin_id" name="admin[admin_id]" required>
            </div>
            <div class="form-group">
                <label for="admin_email">Email:</label>
                <input type="email" id="admin_email" name="admin[admin_email]" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="admin[password]" required>
            </div>
            <div class="form-group">
                <button type="submit">Login</button>
            </div>
        </form>
    </div>
</div>