<!--Admin Dashboard -->

<body>
    <div class="container-scroller">
        <!-- partial:partials/_navbar.html -->
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">

                <a class="navbar brand-logo" href="<?php echo Mage::getBaseUrl() ?>"><img
                        src="<?php echo Mage::getBaseUrl('skin/images/icon.png') ?>" width=" 100" height="80"
                        alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <li class="nav-item d-flex mr-4 ">
                    <a class="preview-item">
                        <i class="icon-inbox"></i> Logout
                    </a>
                </li>
            </div>
        </nav>
        <!-- partial -->
        <div class="container-fluid page-body-wrapper">
            <!-- partial:partials/_sidebar.html -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <div class="user-profile">
                    <div class="user-image">
                        <img src="<?php echo Mage::getBaseUrl('skin/images/adminimage.jpg') ?>">
                    </div>
                    <div class="user-name">
                        Ankit Singh
                    </div>
                    <div class="user-designation">
                        Administrator
                    </div>
                </div>
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" href="<?php echo Mage::getBaseUrl('admin/catalog_product/form') ?>">
                            <i class="icon-command menu-icon"></i>
                            <span class="menu-title">Product Form</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?php echo Mage::getBaseUrl('admin/catalog_product/list') ?>">
                            <i class="icon-box menu-icon"></i>
                            <span class="menu-title">Product List</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?php echo Mage::getBaseUrl('admin/catalog_category/list') ?>">
                            <i class="icon-pie-graph menu-icon"></i>
                            <span class="menu-title">Category List</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?php echo Mage::getBaseUrl('admin/banner/form') ?>">
                            <i class="icon-pie-graph menu-icon"></i>
                            <span class="menu-title">Banner Form</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<?php echo Mage::getBaseUrl('admin/banner/list') ?>">
                            <i class="icon-pie-graph menu-icon"></i>
                            <span class="menu-title">Banner List</span>
                        </a>
                    </li>

                    <!-- </li>
                    <li class="nav-item">
                        <a class="nav-link" href="pages/forms/basic_elements.html">
                            <i class="icon-file menu-icon"></i>
                            <span class="menu-title">Form elements</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="pages/icons/feather-icons.html">
                            <i class="icon-help menu-icon"></i>
                            <span class="menu-title">Icons</span>
                        </a>
                    </li> -->
                </ul>
            </nav>
            <!-- partial -->

            <div class="main-panel">
                <div class="content-wrapper">
                    <div class="row">
                        <div class="col-sm-12 mb-4 mb-xl-0">
                            <h4 class="font-weight-bold text-dark">Hi, welcome back!</h4>
                            <p class="font-weight-normal mb-2 text-muted">MARCH, 2022</p>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</body>

</html>